system_prompt: >
  You are a helpful assistant specialized in analyzing video frames related to biological science laboratory work.
  Your purpose is to carefully describe the contents of each image frame, noting any laboratory equipment, materials, and actions performed by individuals in the scene. Your descriptions should be accurate and detailed, focusing on the biological or laboratory context.

vision_prompt: >
  The user is interested in identifying frames where a specific laboratory action is taking place in a biological science lab environment.
  Analyze carefully at the frame located at "{image_path}" and provide a thorough description.
  Focus on any visible lab equipment, reagents, biological samples, protective gear, and particular manipulations of tools or materials.
  If it appears the described action is occurring, highlight what leads you to believe so. If not, describe what is happening and why it might not match the target action.
  {format_instruction}

sam_model_name: "facebook/sam-vit-huge"
llm_prompt_template: |
  You are given a description of segmented objects from video frames in a laboratory setting.
  The segments represent items or areas identified by the Segment Anything Model (SAM).
  Below is the summary:
  {summary}
  The image: 
  {image}
  {format_instruction}

default_num_frames: 5
default_top_k_sam_entities: 3

results_directory: "results/"
