model:
  pretrained: "lmms-lab/LLaVA-Video-7B-Qwen2"
  model_name: "llava_qwen"
  device: "cuda"
  torch_dtype: "bfloat16"
  device_map: "auto"
  load_4bit: true

service:
  resources:
    gpu: 1
  traffic:
    timeout: 300
    concurrency: 1

video:
  max_frames: 64
  default_fps: 8

defaults:
  image:
    prompt: "Describe this image"
    temperature: 0.2
    max_new_tokens: 512
    context_len: 1024

  video:
    prompt: "Describe this video"
    temperature: 0.2
    max_new_tokens: 512
    context_len: 1024
    fps: 8

  twelvelabs:
    base_url: "https://api.twelvelabs.io/v1.3"
    language: "en"
    provide_transcription: false
    enable_video_stream: true
    prompt: "Provide a detailed and technical summary of the video."
    temperature: 0.7

environment:
  cuda_alloc_conf: "expandable_segments:True"
