model:
  pretrained: "lmms-lab/LLaVA-Video-7B-Qwen2"
  model_name: "llava_qwen"
  device: "cuda"
  torch_dtype: "float16"
  device_map: "auto"
  load_4bit: true

service:
  resources:
    gpu: 1
  traffic:
    timeout: 300
    concurrency: 1
  load_from_db: true

video:
  max_frames: 16
  default_fps: 1
  force_sample: true
  chunk_size: 8

defaults:
  image:
    prompt: "Describe this image"
    temperature: 0.2
    max_new_tokens: 4096

  video:
    prompt: "Please describe this video in detail."
    temperature: 0.2
    max_new_tokens: 4096
    fps: 1

  twelvelabs:
    base_url: "https://api.twelvelabs.io/v1.3"
    language: "en"
    provide_transcription: false
    enable_video_stream: true
    prompt: "Provide a detailed and technical summary of the video."
    temperature: 0.7

environment:
  cuda_alloc_conf: "expandable_segments:True"
